-- Native simulator controls backed by the existing MULA calculation source.
-- The previous simulator.formula.settings.v1 document is preserved for rollback.
begin;
insert into public.cms_content_blocks (content_key, route_path, element_type, fallback_content, draft_content, published_content)
values ('simulator.mula.settings.v1', '/simulateur', 'paragraph', '{"enabled":true,"sourceSerial":"6535194A4DB03","title":"Simulez votre revenu en portage","description":"Calculez vos revenus ou votre taux journalier moyen à l’aide de notre simulateur.","disclaimer":"Ce simulateur est indicatif et n’a pas de valeur contractuelle.","modes":{"tjm":"enabled","revenue":"enabled","gross":"enabled","net":"enabled","total":"enabled"},"defaultMode":"tjm","managementFee":5,"fixedFee":0,"expenses":0,"days":20,"contract":"CDI","fields":{"managementFee":"disabled","fixedFee":"hidden","expenses":"enabled","days":"enabled","contract":"enabled"},"allowCDI":true,"allowCDD":true,"calculateEnabled":true,"showResults":true,"showDetails":true,"pdfEnabled":true,"contactEnabled":true,"contactLabel":"Contacter un conseiller","contactHref":"/rendez-vous"}', '{"enabled":true,"sourceSerial":"6535194A4DB03","title":"Simulez votre revenu en portage","description":"Calculez vos revenus ou votre taux journalier moyen à l’aide de notre simulateur.","disclaimer":"Ce simulateur est indicatif et n’a pas de valeur contractuelle.","modes":{"tjm":"enabled","revenue":"enabled","gross":"enabled","net":"enabled","total":"enabled"},"defaultMode":"tjm","managementFee":5,"fixedFee":0,"expenses":0,"days":20,"contract":"CDI","fields":{"managementFee":"disabled","fixedFee":"hidden","expenses":"enabled","days":"enabled","contract":"enabled"},"allowCDI":true,"allowCDD":true,"calculateEnabled":true,"showResults":true,"showDetails":true,"pdfEnabled":true,"contactEnabled":true,"contactLabel":"Contacter un conseiller","contactHref":"/rendez-vous"}', '{"enabled":true,"sourceSerial":"6535194A4DB03","title":"Simulez votre revenu en portage","description":"Calculez vos revenus ou votre taux journalier moyen à l’aide de notre simulateur.","disclaimer":"Ce simulateur est indicatif et n’a pas de valeur contractuelle.","modes":{"tjm":"enabled","revenue":"enabled","gross":"enabled","net":"enabled","total":"enabled"},"defaultMode":"tjm","managementFee":5,"fixedFee":0,"expenses":0,"days":20,"contract":"CDI","fields":{"managementFee":"disabled","fixedFee":"hidden","expenses":"enabled","days":"enabled","contract":"enabled"},"allowCDI":true,"allowCDD":true,"calculateEnabled":true,"showResults":true,"showDetails":true,"pdfEnabled":true,"contactEnabled":true,"contactLabel":"Contacter un conseiller","contactHref":"/rendez-vous"}')
on conflict (content_key) do nothing;
insert into public.cms_content_versions (content_block_id, version_number, content, format, action)
select id, published_version, published_content, published_format, 'seed'
from public.cms_content_blocks where content_key = 'simulator.mula.settings.v1'
on conflict (content_block_id, version_number) do nothing;
commit;
